### ISSUE TITLE
Suggestion: Allow /tpa a to be used as /tpaccept

### ISSUE THREAD

**Issue by DronXa** [Kr4ken-9/NewEssentials#103]
Many users are used to the fact that /tpa a accepts incoming teleportation, after changing to NewEssentials I have recieved numerous reports regarding this.

**Comment by Trojaner** [comment]
You can do this by editing OpenMods commands.yaml

**Comment by DronXa** [comment]
I have tried to set an alias "tpa a" with higehst priority and I still cant get it to work

**Comment by DronXa** [comment]
Nvm, figured it out!
