### ISSUE TITLE
Add commands aliases, /home would be possible to turn in /h

### ISSUE THREAD

**Issue by Corazun** [Kr4ken-9/NewEssentials#111]
Everything in title, could be in translations with an aliases array

**Comment by DiFFoZ** [comment]
Already possible with `openmod.commands.yaml`

**Comment by Corazun** [comment]
Hello, thanks and sorry for misanswering. Maybe it could be worth to edit a documentation with all of the features and the use of every config files (per example it's difficult to setup the autobroadcast without any help)

**Comment by DiFFoZ** [comment]
I think this is in TODO: https://github.com/Kr4ken-9/NewEssentials/issues/16
