### ISSUE TITLE
Issue on /home command not being smart

### ISSUE THREAD

**Issue by Corazun** [Kr4ken-9/NewEssentials#113]
![image](https://user-images.githubusercontent.com/54606072/126968968-f649de1a-2e12-4863-8709-6c9b78bfe74e.png)

When not owning any bed the plugin will try to teleport instead of cheking before for a least 1 available home (plus displaying empty argument making the message broken)

**Comment by DiFFoZ** [comment]
#106 already reported

**Comment by Corazun** [comment]
Closing it then.
