### ISSUE TITLE
Invalid or outdated plugin assembly: New Essential

### ISSUE THREAD

**Issue by setpopa** [Kr4ken-9/NewEssentials#119]
Im getting this error when loading my server: Invalid or outdated plugin assembly: New Essential
My OS: Ubuntu 20.04 64bit

**Comment by DiFFoZ** [comment]
This plugin is for openmod. Install OpenMod to use this plugin: https://openmod.github.io/openmod-docs/userdoc/installation/unturned.html

**Comment by setpopa** [comment]
The plugin did not work despite the installation of open mod but then I tried to install it via command and it worked.
