### ISSUE TITLE
No commands work when installed, and there is zero documentation/wiki on what commands there are.

### ISSUE THREAD

**Issue by RainOfPain125** [Kr4ken-9/NewEssentials#120]
Title. Cant spawn things, give people admin, etc at all.

**Comment by DiFFoZ** [comment]
in `help.md` there's a small description about commands.

**Comment by Trojaner** [comment]
You can also use openmods /help command

**Comment by RainOfPain125** [comment]
Sorry this wasn't an issue with the plugin, it was a bizarre error caused by something else.
