### ISSUE TITLE
the /home command teleports the player to his bed and back

### ISSUE THREAD

**Issue by G-Aaliyah** [Kr4ken-9/NewEssentials#129]
this problem exists in uEssentials and NewEssentials

**Comment by CyberAndrii** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2890

**Comment by Kr4ken-9** [comment]
Supposedly fixed by Nelson per https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2890#issuecomment-979529043, and also unrelated.
