### ISSUE TITLE
kits not working for my ranks

### ISSUE THREAD

**Issue by Eliteskelly101** [Kr4ken-9/NewEssentials#130]
I have a kit that I want a VIP rank to have but its not working they have permission to do /kits and /kit but I'm trying to give them access to a certain kit and this is the only permission I have found for this plugin is !Kr4ken.NewEssentials:kit.vip and I've tried multiply other things like NewEssentials:commands.kit but all it just says is you dont have access to kit vip and when i do /kits it says i have no kits

**Comment by Zawodowiec1532** [comment]
Try: NewEssentials:kits.kit.xxxx
Where xxxx - kit name

**Comment by THEATLAS23** [comment]
> Prueba: NewEssentials:kits.kit.xxxx Donde xxxx - nombre del kit

worked

**Comment by archie426** [comment]
closing, if it isn't working msg and i'll reopen and take a look (:
