### ISSUE TITLE
permissions for warps

### ISSUE THREAD

**Issue by BDSoriginal** [Kr4ken-9/NewEssentials#135]
warps are working for admins but not for default players i have tried messing with the permissions and nothing has worked

**Comment by JayXTQ** [comment]
Hi, I looked through the code and I have found the solution which I needed too: `NewEssentials:warps.name` is the correct code for your permission groups, replace "name" with the name of your warp and people should have access to that warp

**Comment by archie426** [comment]
closing for now - let me know if this isn't working still
