### ISSUE TITLE
/jump Ignores Ground

### ISSUE THREAD

**Issue by Kr4ken-9** [Kr4ken-9/NewEssentials#19]
/jump works for jumping to any type of object except the ground. It will say you are not looking at anything, which means Physics.Raycast returned false or hit.transform was null.

99% sure it's a layermask issue. Looking at Unturned's code we are using the correct layermask for detecting the ground though. Pretty frustrating

**Comment by archie426** [comment]
We could try and use the item block one as they should have the same behaviour

**Comment by Kr4ken-9** [comment]
Fixed in https://github.com/Kr4ken-9/NewEssentials/commit/21057bad23fab9591b91e2244872b08993634702

I looked at how items are dropped and I realized I am trying to teleport to a transform and not the point where the raycast intersects... I think I was tired when I wrote it lmao. It's fixed, thanks for having me look at items

**Comment by archie426** [comment]
Lol nice
