### ISSUE TITLE
Review Afk Checker

### ISSUE THREAD

**Issue by Kr4ken-9** [Kr4ken-9/NewEssentials#21]
Possibly convert to just a long-running task instead of a service? Now that it is using session data there is not much reason for it to be a service. (Besides decoupling?)

Right now it's kind of messy to configure it as a service. I would like to hear opinions on whether it should remain a service or not.

**Comment by archie426** [comment]
A PlayerSessions service and handle the data through that (as well as other stuff). Not sure how OpenMod handles this but I expect we will need to do some of it ourselves.
