### ISSUE TITLE
Commands Not Working Properly

### ISSUE THREAD

**Issue by papershredder432** [Kr4ken-9/NewEssentials#34]
`TPHere <Name>` always teleports you to yourself
`God` doesn't prevent you from dying from explosions, radiation, (probably hunger/thirst as well)
`Heal` only heals health, broken bones, and bleeding. (unless it isn't supposed to max out your oxygen, hunger, thirst, and radiation)
`Set (Home)` doesn't do anything

**Comment by Kr4ken-9** [comment]
Fixed by #35
