### ISSUE TITLE
Teleport Delays

### ISSUE THREAD

**Issue by Vitael7** [Kr4ken-9/NewEssentials#44]
Can you add an option to delay the teleportation of /tpaccept and /home commands.

**Comment by Kr4ken-9** [comment]
Yes, I would like to implement this. It may take a while though, I am busy lately

**Comment by Kr4ken-9** [comment]
Fixed in https://github.com/Kr4ken-9/NewEssentials/commit/e864ed350b5d346ecca82b895ef74ad5d3a44632
