### ISSUE TITLE
kits issues

### ISSUE THREAD

**Issue by benjaelbsrboi** [Kr4ken-9/NewEssentials#45]
when u crate a kit, the things is been drop inmediatly and isnt equip automatically, please fix it

**Comment by Kr4ken-9** [comment]
I believe this issue is related to OpenMod, I will open an issue in that repo and link it here.

**Comment by Trojaner** [comment]
Can confirm issue is related to OpenMod itself, will try to fix tomorrow

**Comment by IAmSilK** [comment]
Fixed for the next OpenMod update

**Comment by Trojaner** [comment]
Closing here since the issue is fixed in OpenMod
