### ISSUE TITLE
/item needs some polishing

### ISSUE THREAD

**Issue by gegtor** [Kr4ken-9/NewEssentials#53]
uEssentials had great `/i` command for example

**-When spawning something by name it would output the id**

**-`/i "bootleeed water"` would still spawn you a Bottled Water so when using `""` it would be cool if it matched the closest item by name**

**-For example `/i roll` in uEssentials spawns a black bedroll since it's the first matching id in game and Newessentials spawns a red one for some reason same with `/i drum` uEssentials spawned military drum and Newssentials spawns ranger one**

**It's even worse with for example `/i colt` Newessentials spawns 1911 magazine instead off colt**

**Some integrations rely on getting it right like shops and literary 4 years of muscle memory for some players**

**-Rich colored output would be a nice touch**

**Comment by gegtor** [comment]
For some reason /i can't be called from console

```
[17:41:53 INF][OpenMod.Core.Commands.CommandExecutor] Actor console/Console has executed command "i".
[17:41:53 INF][RocketMod] OpenMod.Unturned >> This command can't be called from console
```

**Comment by DiFFoZ** [comment]
Use instead `giveitem` (`gi`)

**Comment by gegtor** [comment]
Is there a reason for /i to be disabled in console?
