### ISSUE TITLE
/tphere does not work

### ISSUE THREAD

**Issue by keszi** [Kr4ken-9/NewEssentials#78]
when I write it this error occurs: https://del.dog/tiwycrager.txt

**Comment by ackrite187** [comment]
Same error here. I can teleport myself to myself, but anytime it's other players, I get that exact error in console.

**Comment by Kr4ken-9** [comment]
I have published a potential fix for this error that you can test by updating to version 1.4.8 of NewEssentials. Please update and try it out and report back if it works.

**Comment by Kr4ken-9** [comment]
Assuming this is fixed since there has been no further response.
