### ISSUE TITLE
Kits System

### ISSUE THREAD

**Issue by Kr4ken-9** [Kr4ken-9/NewEssentials#8]
Kits will be YAML-based. Anyone should be able to edit raw YAML files. It's really easy. Commands for editing the YAML files will come later if they prove to be necessary.

- [x] Commands
  - [x] /kit
    - [x] create
    - [x] remove
  - [x] /kits
- [x] Cooldowns

**Comment by Kr4ken-9** [comment]
YAML is treated as purely data storage now. Users should not be interacting with it, and instead managing kits through commands. There is less granular control but it's easier this way.

**Comment by WertyEziek** [comment]
Please add the option to disable kits commands because other commands from this plugin will be useful to me but I would have to disable kits commands
