### ISSUE TITLE
Missing Commands

### ISSUE THREAD

**Issue by TeemoCell** [Kr4ken-9/NewEssentials#81]
`speed [Amount]`
**Change your movement speed.**

`unlock`
**Unlock any vehicle on sight.**

`lock`
**Lock any vehicle on sight.**

`salvagetime`
**Change your salvage time.**

`openstorage`
**Force open any storage!**

`opendoor`
**Force open any door!**

`jumpheight [Amount]`
**Change your jump height.**

`destroy`
**Destroys the barricade, structure or Vehicle that you are looking at.**

**Comment by gegtor** [comment]
+1

**Comment by MihailHavenT** [comment]
+1

**Comment by Kr4ken-9** [comment]
Some would be completed with the next milestone through IcePlugins:
https://github.com/Kr4ken-9/NewEssentials/issues/3

**Comment by TeemoCell** [comment]
but why another plugin? The other version had that too.

**Comment by Kr4ken-9** [comment]
To be more clear, these plugins are licensed in such a way that I can incorporate them into NewEssentials, rather than recreate them from scratch. In this instance, there would be no need to install another plugin.
